language: python
sudo: false
python:
- '2.7'
- '3.6'
install:
- pip install --upgrade tox-travis -r requirements-build.txt
script:
- tox
deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
notifications:
  on_success: always
  on_failure: always
  email: false
