jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: aqQUinVzbLm2P24mJS8n+0f/LBES6RPb7yX4op6hZFWuHKGBExjyrpxXWeZUaPOpPQIDHhsxcmuvWvAbnxwoE8eGX5BwxmSqVSeqsqI6E/hnM1O5WW5ICpdpLjRWY1LfY3QHJyQ/Use1oHUg99Kun9dne+9sgK+Xq7yDpFCpk975wf4xcW8SryXJ8oZ38joGtMySdz4hjdzvo4MnuHMdzzUUU0cdq1swmdfBUA5mzhY0IzKLh+Op3eTXSbWZ4vbtIf09/F+9DMeBRynHfCC04HX24Uk+TVC5eolwKtNZpVvxfywUbXDsjIuvICyfqNcGESGYTqgzRoNAmVxXvHjSS1aEFQTAw7E6Yz74o6cYiHMRckiuontxJfMR1asecn9LrB0efUQ7dsOoC+5vKhg+xUk4yRuwZDfFvYjYBEPPz+7GeYsUJf63diWS1PGCRwTeTvC8H4rG4P504XP0Hn09FNwJtJFroffxyMd7ozMmndrC/KsnL6iv/AMBldh8YbQAUdeURs2b11YMO44ASSDm4u9euZDKvV3+kG3uk8hgQQ0X76Ett2+NkKX6bV94n1xqN60VTrptLO3s1b6a82V3rWh9dDU95FQZioy9L8UedXofewdjBO734oYdIPt2zFkAaLPapoWlU0sM/GkcbXqGbbfXONE/m7MyZvjIwk7p5Hs=
        - secure: uZCOdGTPs72m5HtZ+FmUBtDolMjPTeqbdTeWJRlBvNpRY5Y7hQOiSyZJq8VOCa59HjlvwJFnsZLeHkhrrpkvzuYikZg4ujIh5PBr8aXBzmOepXQeD6D20H80RnhZpXxKW+YI8tbl3IhiyLpiR2RGQajfHe7sXfLK8BVFxVZQ7SgvukVgu/znPVCNi/ast9pzPkrh7EZSXMVa6Rn71o1e5sxzPD/W7kwoIq8nPnbXRAtysSkupNjMA1UBClPoP/Sl/M0cVGVvh61coqnyWpaEHtmqxj81+lErR7H0Fliw7Z5RLHa0dILrsExGjS9t+MLdI8R8W9vAWbxNda9bh/Eb0kKXvUt3hKLQg8ayRriog6sJlT/QdRuJVFabqkXWljEV2HZ7dbMN4nYBnUfVoGMmM4nTNW0HbMe/4vdylCpCzgIKRVb7gYLY74BTVg3x6ateAJRXXR/qFes7bYgxN2v3HVNIMuFMmYUaWY9imABq2ngd1AsvFVvdOkvqvW59fIjS+jhF3rFsbKvX5TvE+78RUhW0FdcCuXWxjFqAOoAP/DiUYNMmWz1EKghIKM4q9db1CGwCTXCq2TpDb4gTSi+JKEZU1FqL2FHKkDWRhrJMRL7z+omyyGPWaUdRVdGazDFzgJKnawTDE5Z6RGlowt3plR/xw+4IJ+hDv75b1gxclZ4=
        - secure: iR8JA5ztitm3w2A/cw6Ha4ySmJmcTHSdKrC9BB4vjK0lmO874dxjnnXC76YMx3POHNEbqh5mp1otSejmU5goT1tp2kPkYO9Krx33A572x8af/h19FitA06b7h1aeREmDCPssCXBp6tPr6xbphWml6W+hYp5UYr24RCwpGyH5sVXbQh9h0ys73tP+zUda2fBA2npBVbjETrBgzi/4Hz/8KC92A8acP6tCTpPsEn99Ty9f8/XnwoYeaqEE6U5TogB2k7TpMS/0rUOSWFtCUoSlvHrvKoZjPnjCgpRkZ8uyo9EUbQNMU5NlRl6edLt0u31Rrlc+ey6NRgjqh9RYmfbfvZN4nMYPQ31syfgUiZfmiJBKqeY3CMlwjIwFFsEZu3Shgav+w48LKjuvhXtQrWCjEBf1Sr2WTrdT+GAcu4lBYEf34+yeaNGJoWLsRiQ8+JOeTwSLLRNxWvJ/fwZ2CHpukWqDWM/ICXQ1uYx/RpHjxRsSMjXs0KOrPBqL8WbXaz0kPCNpYR0hAJsex/T7XnO9JbvLdbUs4SEQ5WSUxWOSk985vQ0NfG6wkVeUCzyQSCUXC2fxMDxqIBs2No94l1Ri+v39SkRTKBafUFQ31aCNJ/9k1X4mhy1KarsDP0cYlIFhwwsRSJlyie1t4361+qXzuzgvrny2C9SmV8ap4lTGmR4=
        - secure: C5PQsxgxMPTwxSw3sVRHZoAhTc++nrY8mtkrf62OjmPwQTm4tYJTTGFZOUu2TUnALExQNTBbPP4eZfu/ZK1TLHUCELOc0k1PTMpVHmFD7/iyH3oDeNTzafJTVm0OFLE1j6JQa1EaNJzZyLkkRcoy0m8ZWP7xxFFu+v/qWpqjMjpmtaUEWdXzs1pFwN5nTuo7prJZVi8a0Immj53RQQymyjwTVyCG82Bdod5qjrVveIQGMV7NI1ju4f4o7I1hAx34my+gXPhjxljuXGqCkFBf46ZrNLzXY0zyx3M6QD/s2fbHt/rtjYlgibBdYB6jXwz5rf5mYhlooYtJUAlDf3Y9Ai73HH7xcJyIomlcpO8RunLmcj3JwZPsAzQR0+RlRbGeGqnpaaXyOo4XDGAT240tZ5bKX2eQ9B1L25pq01xAynXoIidFpcXtHGTd81zmWTjHcm3R8LCZ2xgEZakEShHRMfPhNiFgGE6izJd2dBk4rusMzL0+MM9vzjkCF7ZGhymKH8WcbgglokeTIa1W5EgpIWP0/6iRTgiuoYk6knxLl4C4JXbyEyebE9UIi7TTWubZMIdiIMWeqWvWlQapYf02DG9K2HOsRCerF/KsIYKE2f30KwGwJFs1DcYmzdWmmjSAOFPo9ihLq4kT/ZzSqruvCxa174uutrijN2MxfzIxx/c=
        - secure: Pl5v+e6TTf2e04YeGJOeexRtL9YCOZva7UlKhnZILKbAep0WP4c7pyM5jC6BvyEB2762DmQM05f9LmsOANMvDRx6j0JjiVckax+1eFvjHeFHCA0H6xLmdos2X9X2Bzc1R6zRhOe2/9QYPJ8o6NApCGvIiFGmQEbd1OSp6/9t0mBKydtIK4XtIw6itwOZ1WPssbch+JSpNEWwHdhtII1irb7POD3oUIN0ogrtgOqZtLtQljv6nZQLpZ3S0/Puf7CG5ftN2NKbq41ZeX/AZYH/K5jlOyolOrEPEP3UphfJ9++Tth5PXdf58UcBNWwRTfbE1qLedfzpRlb/KAH7X2CPcZY/kWtjd+gRUJW+rbCkyW6Lptvi9MU7WnOzyTp5N0hea+Y2oqU7aOzoEEtjk4mMW56iTui36zd3yXKs1/2Pb8jCJ/mqM+LYWWGc8NlD/Ag2dWvmHj8bcyhmdLiJhZUDB5zZhXrwu2P3p5M48P3o/dGoToQtoq9K1iIGEiJyDAlsv5sJ6VNNMTyYfHMEceU31Vid65dQKd/ykJRSYnMjFz11x6zQk878pmPf5uCY9LWAkdYg/6fy3+Jqpdv57KiDV6i9Z/IGitRmEBqooRMZxVdA+kqZpGhF4I+lc+jYriChzrcfqT+CE9ExHGewx3PDPBFpvmMFuZij1JuHDWo3gEo=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: mdxoRJeFoTV0Re/NA5pcPCfDhv2ZFLtyckSojYwQVmAt71WFoGupPJ6KAzr86A0u9stAxrZVMw+m6oRtJYugEyd9R9XkXohcGnwegcGhI78VP6QStAxnxIi3qBa1mDXpr0nlBPtGGLdu763sugK6Xzpxns5XgO3sdt7yAYN9KRC1o3Be7j02IFK9os29PKWgdqlDdkCNPJfSAwkEngKWSzTVp362mXeH9D8SxZZaiYbGHVwRSzZ1aSY0leC0ga04Rrmv9z3+qW3dqztlHgQT9vF8QOE/Y7X9X2hVpZ+7yDV9AMfBQM+l0WgyMTGjpjmRMj+QDJIpE4oQSYnPAMK3QHoKkbvJIkbi1c8iutcKLBHwFBfMANPLTo40nUptfTXn22vNviWsviPesop38TJHe/7u8/5H6bos9HgzjyOKUicIbIXtcvoD46vXyuqUprlgrXKAJ+C8f36Rp8blqhx2c4YjmS/My2DlSBSZdjo7teY5oVCA7xthbeqSmduLKpMkZ7XjXSg3/eobqq4hF8upLJxKsr+U70j9DnRpdQ4GuOZ3sFaFee/BaFEv5wvV5MUthS/hgGfgQKilxxIYiGsQT7lPfyA/osbKHMjSINIAMbtKA4DLU9r/poncx/mY9BZbE3iy/K/a0mRBV//5D5KD1vNLmnIj898G9rVtutyB5NI=
        - secure: aDVPt28ADL2UkZOo4OJlT3oBBXTpYIxRoU1Zku1010w3msiBQUFbWsTxXsFyKvNcslPSoycR81n4Kh9jEgZShEFtktnQ08MMs0mqm5YC/I1C158k44BacHt4ibrg16DkbllwjMpwwIPWnwZF+126+1vMDrtBJS/0/RLeEJl+Wf4rsuaX4GkazVLol6A2DrJbUzuZGQunnL/b0jb7Nj+jBBbJ5nvMIO2rCDhN5iYT+te+zILpT06jL2nXxLSpQ8JZzIxxMeCzbkIAILblXsIXeN0zQ1JiUS+SF7LBdscEzMiBn+44iHGYURDmysX+1rRTW/vJeDW0eLcWiq3qh+1j4KkZUohECCP6pgf1JLGBIVxBBEQ7pgFaLgsyoPWWnUkX+F8R4G6zyK82UShiyCG8UpWDp68YyTSX0ctYfG+AQ/6Q4wOM5t8ggLUl+CN9b3gRhTOXmywLK50z3I/jYcUnl4DhpseNb7W2bgPiSJWfaZpZWR6sPN7KZEs+vt+/PpAH3GmvyB1fWGIyex/vgtiOHCcgTbSlxZLA9exHl/sJQzycMayxL9v4il9i9oG+Fvh4X/MSHrqj5ExPE7OJ49j3eB5BGohrk9YQ2gGBSMEzsmZwJr/+Tt9E6hY7LxLn+epuEYCSvQlE4zyB439zbbsdIcGDaIfNaL6VmMg9Vhptwsk=
        - secure: upOENuvx25+hjmNY63ifNtfNWfAMoVzN3PW/AsHhyn8w300kFtHRviUYA1qq3EFYC7VAxsrU4RkXDauJmyQHWgGqRUzPMhEhbs/3YCwp6STjjrYQU47qJhm62uvltwIEnEp+NCRsv3erjCIC6dGQid/1PkAZaLlwmp+ygmlF2c/I4ZCCGKknEtyberq0HQ+0+ZE8flyoTOiCwYu2I0zSk6KFF7UA6oC/AWRyCfkIvfs1xZDJA1hi5RzU07JWdjr9GX7CIdkgMNLZPmmwXjOXFe0soVszwiuTdrugaTmfKtw8+i+xj/3Yr3aYTB9UpgOPtMkFg5Xluj0j7IwOEXjA+v0kaN0fnGvzECPcCmutgAnf1E8CGCoA8vEO5jybGkpZxKBcFmCRw2wX9BH4nuqr7h3guP3DVEhdrrSqQ9yGDPupvy2XEQp+PPWg0brK9O/QOFgbIOGdurPGml2cQEy3bFInb/3EplA0w7R1T/vZvyIJrjAzH1b6+9KMvxcuL+rO3pVgpuJTpN/Shwpqt7woGLYOz98DuXirtG4GUJTVAba4wAJpytmXWtqX4hSsRuG3Gsz+GDQoISluuVInDhk84fJh5Dz1dQ9Jh2p56fSHw0ujkU4X9UFXPIXCmeOXEn0k79ywnQ5Z+jpuakIUuk3N3J+q6bEHliSWnF/UXsy37l0=
        - secure: kFKeP3a6t2AKKJtrQOVH3QeiMlIL21lxUKD8G6gt/AgaC7My/5DsPUB9t9+u6Hr3y4BOEKUxDW7ElmfFXSG2nA6XHlq3fz+95PKi8OdwzNpeHF/ncs27EFYqiCEhGBT6gzA9hyWZiYF/y1niscmfyPTJPZcz/7Ph9dqHKRFUHUAlscDSQCfU4wg5GdRCgxQPSpqRlFzQgj6xovAwEDkpin9Iy6YtMBOW+RywOqYsP3zd7Le3sP66w0GEI6bARveU4fFXu2dCOC3pOe+bGLVu67QO5t1DeYfxQyG4iFzyYlDuaw4O1enLLpGEA7hpvicmRx6tir7tPa27CYJ5inpj7P0peSSbOH9KQVRfA1S+qcOEy/u5+9snDHyZ4+3tu0BWq7EUJBy6e8fu+0EbEPSf5gFGrUpOlDyNzQ/QjnkpLDCbzugRHFruUelKDBQEe5bYwwaiYaowA/ZjSDrpnQoMLXaI4Clc7ZrO7MkI1sTnquTrW7KcsbX/7o63xrM/IsWX7NETOA/lB6BiMfbvRaZba5WaFDdtgnTC8mqhidKk9MvVSxOW+XAKPfxCmQcppzFB1CQQH9odroq0erjz5vEVsZD8JsACF8hkAL5JDWCFT+nuy2dJiicVc7r+2HQIKC7z5pVXnhsH0MKpnFyY31LbVBuVBw+M+OlPZohTBiMCMhk=
        - secure: vo/fYRUyc1g4doD522il+UTA1mFzMK/j/hYQ/B1+oa6Ukn/bKXuhHZHLRiddwIYydXo7i/AgET8Ja8ETr4ZmbGcRZIHsFy17RvMf122ZKAfVzwkVeZzZHkqIxJAy5uX/JXkPaH/HyYet2H/DyaWXfkMKILWPXrOwg5EElE8nsJh7O3zkUD9eMDLVAJNVkrsfZ060FueCacKG6/QfLIZHtwOsqPH1/v7MaMS5BWhyBgCAWpxlYLrByX7WH3H1bL//v7MD3e5/k0jwP/pEBatnyLFoae7I/sFypI90YgSa0angKUSdKRxfXwByVADDobCn38adyVwVm001zeshBoyPtgQq3xKfaFh4unxZUXiCBvs3c8tsZVZNdxCXk0Jj9ZI1f37R5+suMr4jSFs5FV0p04eLx8icco7Foh7RHEZR6AfSYknPO3eYOfi/IhQoH71BBXB5X972iSCZjU7mZbQ3N0+QsV2uSZs3npXOYqEeCWa9DD3TFaIi8xNK85gfALBeRGpVGnIVd2ycnzvRrafMJ6kJ7AINiumK04mIV/s2cWhGrSCjPw85ufrbEWlstz9eVFnENZa9UvBxDXcUhMmIB9lezoQiyn5Baz2936n5dzJZ36Dfcepgg1LxPfU4PCZA5FZ9l/K5NuG3tRt4SxGXckJJWsCryJ+Vltu4TLkLkRA=
install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- python .multipackage/scripts/test_by_name.py typedargs
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: BGEjhHLpYOJP2dWrIiVNtH5wOX87VaDFdowIn2ZhurcDM8CyQ04pzMk5vh7NUbReWVEQUEixP9OKm/esdvX0TGHLkfXQMxSIAhXN8LKWeyESQeINlpT/P6pZoSGxzuhhuW8npZo5qiBaPNHHn6snDJ1RjyI4xxKMaYdzYZjMlPgVW5SY0WnIWtjgWIVvGGxzAHC8fE6TnQ81zdRgX1NIknc63flJSNmMli42Yya2NyQtvaylz33qCivSW6UwN+SAjuZG0AOX2l2zEXbjg3P80mMu+hL3rEhQHFsZpBK/qstNgakpl/C5ngwwF4qk/2ZxcVZjZFtcxkRwW/sRVgm2uOTxNelI8A91kGNmt3d2CFHEgmp4USUFzGnp6bPBpR8ZjJ/IsbiZZBGODMY71xtFU0m5o+qXlvmwxGnXaPNQQpO6AwN5xRIyNG/64MyZ2LU+Wbg+f8ULRxS+1wn0CWBhv3VOYhcbVKEa6WcWZLadrL7hulUhs7PpoHwTH4CceXXB62FDRxNA36c7/aXA6+OTch2dJMBmiAypeoIhCk4I02B0A4yYjza7Jl2QSFzpEkTZpxLvabbY0svJ5FGx+ZlFoUdZ5I7IuEWPp9Mtd7tjP5jU2AGq6cl2CytBzAOKfPEsovfPUesiLpT6rKSCK5oU3EiipryxBojI4MAqEqd3Oi4=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always