language: python
sudo: false
python:
- '2.7'
- '3.6'
install:
- pip install --upgrade tox-travis -r requirements_build.txt
script:
- tox
deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: NeEQfzUHcb1Pr5+zSauy7Hb3jIVyff2+YTzbXDzXi/ygbU1lnJGmWljXTJIihAGOZ+RDC8EnxjYmSjqp+9KEtCXbMxf7QoEWJePQIP/+t4kPvJred88UUxYa9z2Ku8epOFbUaoFL5bbltAMU45fg7grjJPoD7A1mvuVum8Sxb+599JpzPB7hLwLOLbmyYJP2d6tjuAhmt2ns3J/lwqBOEVCglSaIWxm6TbWfRo/CxpZAj4jD/XBULdvz5VnSizgaodNAyJxMLTmvZ0hmPLpN9Mb4THe6jq41fYWyvdP7m0JKf/+e/V35t1WIxHKw1XSXROjT2HjjQRiSeRSDwCetWOmHWy3DwNVuZ9CrNUrZE+FZbP2M9CAhvgsUgcu25XTwNtK53sk0g6siXoKYM34qZGrSFU69dQd0AJ6tISon2V7tBYUq4w+MpJj4K6E3qetGq6sZMNiRrd+v43xLIpfPi+MhAC7QckMPWB4mKpv8rnytAnOTDuTtNIKybyvpNanna1eu9ijofB0bzf/f45gXnabrIBtOtZ0K9M0jsjohBt7sv3yn8r65FCsq6pW/KdSJGUaPdrP7eOVwfxh6ZO815sDgZeVc2AXNJIUdnha4oHLIPOh0tq8gPUu48Tief+oYo2RJ92uMZ7B8MAWKmlknrnnjGAhPeT6UryonwMPq/1A=
